from .keywordRequest import keywords
from .regular.calc import calc
from .regular.delete import delete
from .regular.help import helpKW
from .regular.open import openKW
from .regular.uranium import uranium
from .games.menu import game
from .games.guess import guess
from .games.rps import rps
from .regular.whoami import whoami
from .regular.time import time
from .regular.date import date
from .regular.clear import clear
from .notes.note import *
from .regular.chpassword import chpassword
