from .keywordRequest import keywords
from .calc import calc
from .delete import delete
from .help import help
from .open import open
from .uranium import uranium
from .games.menu import game
from .games.guess import guess
from .games.rps import rps
